### PR TITLE
Support PHP 7.4

### LINKED ISSUE #37: Support php7.4
Is it possible to update the PHP package requirements to support php7.4?

### PR DESCRIPTION
**Pull request by ahinkle**
This PR allows support for PHP 7.4 as Magento 2.4 supports PHP 7.4.

Looked through the code -- no deprecated functions from 7.3 -> 7.4 discovered. 

Closes #37 .

### CODE REVIEW

**Comment by markhedberg** [comment]
Thanks @ahinkle - Please merge for PHP 7.4 support

**Comment by mswo98** [comment]
Thanks @ahinkle - Please merge PHP 7.4 support

**Comment by mswo98** [comment]
Thanks @ahinkle - Please merge PHP 7.4 support, Please update this we need this on urgent basis.

**Comment by jasperzeinstra** [comment]
@afirlejczyk I would also love to see PHP 7.4 support.

**Comment by mamsincl** [comment]
Magento 2.3.7 also working with php7.4 ... please resolve it

**Comment by mamsincl** [comment]
@pkarw, please

**Comment by brucemead** [comment]
Bump

**Comment by brucemead** [comment]
@pkarw @afirlejczyk are either of you able to review this PR please?

**Review by pkarw — APPROVED** [review]

**Review by pkarw — APPROVED** [review]

**Pull request merged**
